name: ceasar_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  flutter_animate: ^4.5.0
  http: ^1.1.0
  intl: ^0.18.1
  supabase_flutter: ^2.3.4
  mongo_dart: ^0.9.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  flutter_markdown: ^0.6.20+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/profile.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/backg.jpg
